# Generated by Django 3.0.8 on 2020-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring',
            name='account',
            field=models.CharField(default='checking', max_length=8),
        ),
    ]
