# Generated by Django 3.0.8 on 2020-08-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='condition',
            field=models.CharField(max_length=12),
        ),
    ]
