# Generated by Django 3.0.8 on 2020-08-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200829_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
