# Generated by Django 3.0.8 on 2020-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200830_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlists',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='auctions.AuctionListing'),
        ),
    ]
