# Generated by Django 3.0.8 on 2020-09-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200903_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
